version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: health
      POSTGRES_PASSWORD: MtoNudjaYUDbzvyZRt5phjiC2ITLjb
      POSTGRES_DB: ds_health
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
